#!/bin/bash
#PBS -N nhsg12m
#PBS -l select=1:ncpus=64:mem=435gb
#PBS -l walltime=02:00:00
#PBS -J 1378-1379
#PBS -o /home/users/nus/e1184420/scratch/nhsg12m/logs/nhsg12m_%I.out
#PBS -e /home/users/nus/e1184420/scratch/nhsg12m/logs/nhsg12m_%I.err

echo "=== Task $PBS_ARRAY_INDEX starting on $(hostname) at $(date) ==="

module load miniforge3
echo -e "\nLoaded modules:"
module list 2>&1

cd ${PBS_O_WORKDIR}
echo -e "\nWorking directory: $PWD\n"

# activate your conda env
conda activate p2g

# parameters
# CLASS_DATA=/home/users/nus/e1184420/research/NHSG-12M/poly_class_dataset/ParamTable_demo.npz
CLASS_DATA=/home/users/nus/e1184420/scratch/nhsg12m/ParamTable.npz
SAVE_DIR=/home/users/nus/e1184420/scratch/nhsg12m/poly_class_dataset
CLASS_IDX=$PBS_ARRAY_INDEX

echo "Processing class $CLASS_IDX"
python /home/users/nus/e1184420/research/NHSG-12M/generate_poly_class.py \
    --class_idx $CLASS_IDX \
    --class_data "$CLASS_DATA" \
    --save_dir "$SAVE_DIR" \
    --num_partition 5 \
    --short_edge_threshold 30

echo "=== Task $PBS_ARRAY_INDEX finished at $(date) ==="